# CodeRabbit Configuration
language: "en-US"
reviews:
  profile: "chill"
  auto_review:
    enabled: true
    draft_pr: false
    ignore_title_keywords: ["WIP", "DRAFT"]
  path_filters:
    - "!**/node_modules/**"
    - "!**/.turbo/**"
    - "!**/dist/**"
    - "!**/build/**"
    - "!package-lock.json"
  instructions: |
    Perform a comprehensive review of the code changes.
    - Check for security vulnerabilities.
    - Ensure adhering to best practices for React, Node.js, and TypeScript.
    - Look for potential performance bottlenecks.
    - Verify that the code follows standard JavaScript/TypeScript style guides.
chat:
  enabled: true
